language: python

python:
 - "3.7"

install:
 - pip install -r requirements.txt
 - pip install coveralls
 - pip install codeclimate-test-reporter

scripts:
 - pytest --cov-report term-missing --cov=app

 after_success:
  - codeclimate-test-reporter